/**
 * workflow-api.ts — complete typed API for the Sandman order workflow.
 *
 * This is the single source of truth for:
 *  - signal / query names and their payload / return types
 *  - order lifecycle state and supporting domain types
 *  - task-queue and workflow-type constants shared by the worker and client
 *  - the FEATURES list consumed by the control-plane and explainer panels
 *  - the WorkflowEventType union used by the live event rail
 *
 * `sandbox-template/shared.ts` is a standalone mirror of the workflow-facing
 * half of this file (it ships into the E2B VM where `src/lib` is absent) —
 * keep the two in sync.
 */

// ---------------------------------------------------------------------------
// Monetary primitive
// ---------------------------------------------------------------------------

/**
 * An amount of money expressed as integer cents (e.g. 1099 = $10.99).
 * All monetary fields in this API use this alias for clarity.
 */
export type MoneyCents = number;

// ---------------------------------------------------------------------------
// Order status
// ---------------------------------------------------------------------------

/** All possible order lifecycle states, in the happy-path order they occur. */
export const ORDER_STATUS = {
	/** The workflow has started and is charging the card. */
	Received: 'RECEIVED',
	/** Payment succeeded; a durable timer runs while we wait for the restaurant. */
	WaitingForRestaurant: 'WAITING_FOR_RESTAURANT',
	/** The restaurant accepted and is cooking; waiting for delivery. */
	Preparing: 'PREPARING',
	/** Terminal: the order arrived. */
	Delivered: 'DELIVERED',
	/** Terminal: the restaurant never accepted, so the payment was refunded. */
	Refunded: 'REFUNDED',
	/** Terminal: the customer cancelled (or payment failed). */
	Cancelled: 'CANCELLED'
} as const;

/** Union of all order status string values. */
export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];

// ---------------------------------------------------------------------------
// Task-queue and workflow-type constants
// ---------------------------------------------------------------------------

/** Temporal task queue shared by the Sandman worker and client. */
export const TASK_QUEUE = 'orders' as const;

/** Temporal workflow type name for the order workflow. */
// MUST equal the exported workflow function name in sandbox-template/workflow.ts —
// the Temporal worker registers workflows by their function name, so a client that
// starts a different string gets "workflow type not registered" against a live worker.
export const ORDER_WORKFLOW = 'orderWorkflow' as const;

// ---------------------------------------------------------------------------
// Domain types used in OrderInput and OrderSnapshot
// ---------------------------------------------------------------------------

/** A single item in an order. */
export type OrderItem = {
	/** Human-readable display name. */
	name: string;
	/** Quantity ordered. Must be ≥ 1. */
	quantity: number;
	/** Unit price in cents. */
	priceCents: MoneyCents;
};

/**
 * Input passed when starting a new order workflow.
 * This is the canonical start argument for `ORDER_WORKFLOW`.
 *
 * `cardLast4` drives the payment demo in the sandbox activities:
 *  - '0000' — the first charge attempt fails, demonstrating automatic retry
 *  - '9999' — the card is declined (a non-retryable failure)
 *  - anything else — the charge succeeds on the first try
 */
export type OrderInput = {
	/** Idempotency key / order ID generated by the caller. */
	orderId: string;
	/** Non-empty list of ordered items. */
	items: OrderItem[];
	/** Last four digits of the demo payment card. */
	cardLast4: string;
	/** How long the durable timer waits for the restaurant before refunding. Default: 300. */
	restaurantTimeoutSeconds?: number;
};

// ---------------------------------------------------------------------------
// Signals
// ---------------------------------------------------------------------------

/** Signal names accepted by the order workflow. */
export type SignalName = 'restaurantAccepted' | 'deliveryCompleted' | 'cancelOrder';

/** Payload for the `cancelOrder` signal. */
export type CancelOrderSignal = {
	/** Human-readable reason for cancellation. */
	reason: string;
};

/**
 * Maps each {@link SignalName} to its payload type.
 * Use this to build type-safe signal-dispatch helpers and `setHandler` calls.
 */
export type SignalPayloadMap = {
	restaurantAccepted: Record<string, never>;
	deliveryCompleted: Record<string, never>;
	cancelOrder: CancelOrderSignal;
};

export const SIGNAL_NAMES = [
	'restaurantAccepted',
	'deliveryCompleted',
	'cancelOrder'
] as const satisfies readonly SignalName[];

export function isSignalName(value: string): value is SignalName {
	switch (value) {
		case 'restaurantAccepted':
		case 'deliveryCompleted':
		case 'cancelOrder':
			return true;
		default:
			return false;
	}
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/** Query names exposed by the order workflow. */
export type QueryName = 'getStatus';

export const QUERY_NAMES = ['getStatus'] as const satisfies readonly QueryName[];

export function isQueryName(value: string): value is QueryName {
	return value === 'getStatus';
}

/**
 * One human-readable entry in the order's story, recorded by the workflow as
 * it runs and returned inside the `getStatus` snapshot.
 */
export type TimelineEntry = {
	/** ISO-8601 timestamp of the event. */
	timestamp: string;
	/** Human-readable description of what happened. */
	description: string;
	/** The order status after this step. */
	status: OrderStatus;
};

/**
 * Full queryable state of a live order workflow.
 * Returned by the `getStatus` query — this is what the control plane renders.
 */
export type OrderSnapshot = {
	/** Current order status. */
	status: OrderStatus;
	/** The order this workflow is running. */
	orderId: string;
	/** The ordered items. */
	items: OrderItem[];
	/** Sum of all item prices × quantities, in cents. */
	totalCents: MoneyCents;
	/** How many attempts the payment charge took (2+ means Temporal retried it). */
	paymentAttempts: number;
	/** Why the order was cancelled, when the customer cancelled it. */
	cancelReason?: string;
	/** ISO-8601 timestamp when the workflow execution started. */
	startedAt: string;
	/** The order's story so far, oldest first. */
	timeline: TimelineEntry[];
};

/**
 * Maps each {@link QueryName} to its return type.
 * Use this to build type-safe query-dispatch helpers and `setHandler` calls.
 */
export type QueryReturnMap = {
	getStatus: OrderSnapshot;
};

/**
 * Summary of one workflow execution inside the sandbox, as returned by the
 * list route. Used by reload restoration to re-attach to a live run — not a
 * teaching surface.
 */
export type WorkflowSummary = {
	workflowId: string;
	runId: string;
	/** Normalized execution status (e.g. "RUNNING", "COMPLETED"). */
	status: string;
	/** Workflow type name (e.g. "orderWorkflow"). */
	type?: string;
};

// ---------------------------------------------------------------------------
// Feature map
// ---------------------------------------------------------------------------

/**
 * Unique identifier for each Temporal feature demonstrated by the Sandman
 * order workflow. This is the authoritative list — the explainer panels
 * render it and the anti-drift coverage test checks it.
 */
export type FeatureId =
	| 'activities-retry'
	| 'non-retryable-failure'
	| 'signals'
	| 'queries'
	| 'timers-durable-sleep'
	| 'durable-recovery';

/**
 * Control-plane action identifier — maps to a button or interaction in the
 * sandbox control panel.
 */
export type ControlId =
	| 'start-order'
	| 'accept-restaurant'
	| 'complete-delivery'
	| 'cancel-order'
	| 'query-status'
	| 'kill-worker';

/**
 * One entry in the {@link FEATURES} list.
 * Every `signal`, `query`, and `control` reference in the list resolves to a
 * name in the corresponding union exported from this file.
 */
export type Feature = {
	/** Stable identifier for this feature. */
	id: FeatureId;
	/** The Temporal concept being demonstrated (rendered as a heading). */
	concept: string;
	/** How the concept is exercised in this specific workflow. */
	mechanic: string;
	/** Optional control-plane action that triggers or showcases this feature. */
	control?: ControlId;
	/** Optional signal that exercises this feature. */
	signal?: SignalName;
	/** Optional query that exercises this feature. */
	query?: QueryName;
};

/**
 * The complete list of Temporal features demonstrated by the Sandman
 * order workflow.
 *
 * Internal-consistency guarantee: every `signal`, `query`, and `control`
 * value in this list resolves to a member of the corresponding union in
 * this file.
 */
export const FEATURES = [
	{
		id: 'activities-retry',
		concept: 'Activities & Automatic Retry',
		mechanic:
			'The payment charge runs as an activity with a visible retry policy. Card 0000 fails its first attempt with a fake gateway timeout, and Temporal retries it automatically with exponential backoff — the workflow contains no retry loop.',
		control: 'start-order'
	},
	{
		id: 'non-retryable-failure',
		concept: 'Non-Retryable Failures',
		mechanic:
			'Card 9999 is declined by the issuer. A decline is permanent, so the activity throws ApplicationFailure with nonRetryable: true — the retry policy is skipped and the workflow cancels the order instead.',
		control: 'start-order'
	},
	{
		id: 'signals',
		concept: 'Signals',
		mechanic:
			'Restaurant acceptance, delivery completion, and cancellation are Temporal signals — async messages into the running workflow. The workflow parks on condition() and resumes the moment the signal it is waiting for arrives.',
		control: 'accept-restaurant',
		signal: 'restaurantAccepted'
	},
	{
		id: 'queries',
		concept: 'Queries',
		mechanic:
			'getStatus returns a live OrderSnapshot — status, total, payment attempts, and the order timeline — without advancing execution or writing history.',
		control: 'query-status',
		query: 'getStatus'
	},
	{
		id: 'timers-durable-sleep',
		concept: 'Durable Timers',
		mechanic:
			'A deadline timer fires if the restaurant does not accept in time, automatically refunding the payment. The timer lives in the Temporal server, not the worker — it survives worker restarts.',
		control: 'start-order'
	},
	{
		id: 'durable-recovery',
		concept: 'Durable Recovery',
		mechanic:
			'The kill-worker button terminates the Node.js worker process mid-flight. Because the Temporal server preserves all workflow state, the workflow resumes exactly where it left off when the worker restarts — the centrepiece of the Sandman demo.',
		control: 'kill-worker'
	}
] as const satisfies Feature[];

/** Inferred type of the {@link FEATURES} constant. */
export type FeatureMap = typeof FEATURES;

// ---------------------------------------------------------------------------
// Teaching scenarios
// ---------------------------------------------------------------------------

/**
 * Stable identifiers for guided workshop scenarios. The IDs are shared by the
 * UI, documentation, and sandbox-template parity tests so the teaching path
 * cannot drift silently from the workflow contract.
 */
export const SCENARIO_ID = {
	HappyPath: 'happy-path',
	Retry: 'retry',
	TimeoutRefund: 'timeout-refund',
	WorkerRecovery: 'worker-recovery'
} as const;

/** Union of all guided workshop scenario identifiers. */
export type ScenarioId = (typeof SCENARIO_ID)[keyof typeof SCENARIO_ID];

/** A mechanically verifiable step in a guided scenario. */
export type ScenarioStep = {
	/** Stable step identifier within the scenario. */
	id: string;
	/** Control-plane action that drives the step, when the step is interactive. */
	control?: ControlId;
	/** Temporal concept the step is meant to teach. */
	featureId: FeatureId;
	/** Binary completion signal used by the UI and tests. */
	completesOn: WorkflowEventType | 'QueryCompleted' | 'WorkerRestarted';
};

/** One guided scenario exposed in the workshop UI. */
export type Scenario = {
	id: ScenarioId;
	title: string;
	summary: string;
	steps: readonly ScenarioStep[];
};

/** Canonical guided workshop scenarios for the Sandman demo. */
export const SCENARIOS = [
	{
		id: SCENARIO_ID.HappyPath,
		title: 'Deliver one order',
		summary: 'Start the workflow, accept the order as the restaurant, and complete the delivery.',
		steps: [
			{
				id: 'start-workflow',
				control: 'start-order',
				featureId: 'activities-retry',
				completesOn: 'WorkflowExecutionStarted'
			},
			{
				id: 'restaurant-accepts',
				control: 'accept-restaurant',
				featureId: 'signals',
				completesOn: 'WorkflowExecutionSignaled'
			},
			{
				id: 'complete-delivery',
				control: 'complete-delivery',
				featureId: 'signals',
				completesOn: 'WorkflowExecutionCompleted'
			}
		]
	},
	{
		id: SCENARIO_ID.Retry,
		title: 'Watch activity retry',
		summary:
			'Use the flaky demo card (0000) to show Temporal retrying an activity without workflow-side retry loops.',
		steps: [
			{
				id: 'activity-completes-after-retry',
				control: 'start-order',
				featureId: 'activities-retry',
				completesOn: 'ActivityTaskCompleted'
			}
		]
	},
	{
		id: SCENARIO_ID.TimeoutRefund,
		title: 'Let the restaurant timeout refund the order',
		summary:
			'Start an order and do not accept it; the durable timer fires and the payment is refunded automatically.',
		steps: [
			{
				id: 'restaurant-deadline',
				control: 'start-order',
				featureId: 'timers-durable-sleep',
				completesOn: 'TimerStarted'
			}
		]
	},
	{
		id: SCENARIO_ID.WorkerRecovery,
		title: 'Kill and restart the worker',
		summary:
			'Stop the worker while the workflow is waiting, then restart it and watch history replay restore execution.',
		steps: [
			{
				id: 'worker-restarted',
				control: 'kill-worker',
				featureId: 'durable-recovery',
				completesOn: 'WorkerRestarted'
			}
		]
	}
] as const satisfies readonly Scenario[];

// ---------------------------------------------------------------------------
// Workflow event types (live event rail)
// ---------------------------------------------------------------------------

/**
 * Concrete Temporal history event type strings emitted during an order
 * workflow run. Each value is a valid `type` string for a `WorkflowEvent`
 * (see `src/lib/contracts/events.ts`).
 *
 * The control plane uses these as completion predicates in the guided-tour
 * rail and to colour-code the live event stream.
 */
export const WORKFLOW_EVENT_TYPE = {
	WorkflowExecutionStarted: 'WorkflowExecutionStarted',
	WorkflowExecutionCompleted: 'WorkflowExecutionCompleted',
	WorkflowExecutionFailed: 'WorkflowExecutionFailed',
	WorkflowExecutionCanceled: 'WorkflowExecutionCanceled',
	WorkflowExecutionTerminated: 'WorkflowExecutionTerminated',
	ActivityTaskScheduled: 'ActivityTaskScheduled',
	ActivityTaskStarted: 'ActivityTaskStarted',
	ActivityTaskCompleted: 'ActivityTaskCompleted',
	ActivityTaskFailed: 'ActivityTaskFailed',
	ActivityTaskTimedOut: 'ActivityTaskTimedOut',
	TimerStarted: 'TimerStarted',
	TimerFired: 'TimerFired',
	TimerCanceled: 'TimerCanceled',
	WorkflowExecutionSignaled: 'WorkflowExecutionSignaled'
} as const;

/** Union of concrete Temporal history event type strings used by this workflow. */
export type WorkflowEventType = (typeof WORKFLOW_EVENT_TYPE)[keyof typeof WORKFLOW_EVENT_TYPE];
