/**
 * workflow-api.ts — complete typed API for the Sandman food-ordering workflow.
 *
 * This is the single source of truth for:
 *  - signal / query / update names and their payload / return types
 *  - order lifecycle state and supporting domain types
 *  - task-queue and workflow-type constants shared by the worker and client
 *  - the FEATURES list consumed by the control-plane and explainer panels
 *  - the WorkflowEventType union used by the live event rail
 *
 * Track D (workflow implementation), Track E (control plane), and Track F
 * (explainer) all import from here. Import only types where no runtime value
 * is needed — verbatimModuleSyntax is enforced.
 */

// ---------------------------------------------------------------------------
// Monetary primitive
// ---------------------------------------------------------------------------

/**
 * An amount of money expressed as integer cents (e.g. 1099 = $10.99).
 * All monetary fields in this API use this alias for clarity.
 */
export type MoneyCents = number;

// ---------------------------------------------------------------------------
// Customer tier
// ---------------------------------------------------------------------------

/** Customer tier — affects priority routing and discount eligibility. */
export const CUSTOMER_TIER = {
	Standard: 'standard',
	Premium: 'premium',
	Enterprise: 'enterprise'
} as const;

/** Union of all customer tier string values. */
export type CustomerTier = (typeof CUSTOMER_TIER)[keyof typeof CUSTOMER_TIER];

// ---------------------------------------------------------------------------
// Order status
// ---------------------------------------------------------------------------

/** All possible order lifecycle states. */
export const ORDER_STATUS = {
	Created: 'CREATED',
	Validating: 'VALIDATING',
	AwaitingRestaurant: 'AWAITING_RESTAURANT',
	Preparing: 'PREPARING',
	AwaitingCourier: 'AWAITING_COURIER',
	InDelivery: 'IN_DELIVERY',
	Delivered: 'DELIVERED',
	Cancelled: 'CANCELLED',
	Refunded: 'REFUNDED'
} as const;

/** Union of all order status string values. */
export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];

// ---------------------------------------------------------------------------
// Task-queue and workflow-type constants
// ---------------------------------------------------------------------------

/** Temporal task queue shared by the Sandman worker and client. */
export const TASK_QUEUE = 'sandman-food' as const;

/** Temporal workflow type name for the primary food-ordering orchestration workflow. */
// MUST equal the exported workflow function name in sandbox-template/workflows.ts —
// the Temporal worker registers workflows by their function name, so a client that
// starts a different string gets "workflow type not registered" against a live worker.
export const ORDER_FOOD_WORKFLOW = 'orderFoodWorkflow' as const;

/** Temporal workflow type name for the delivery child workflow. */
export const DELIVERY_WORKFLOW = 'DeliveryWorkflow' as const;

/** Temporal workflow type name for the subscription renewal workflow. */
export const SUBSCRIPTION_WORKFLOW = 'SubscriptionWorkflow' as const;

// ---------------------------------------------------------------------------
// Domain types used in OrderInput and OrderSnapshot
// ---------------------------------------------------------------------------

/** A single item in an order. */
export type OrderItem = {
	/** Menu item identifier. */
	itemId: string;
	/** Human-readable display name. */
	name: string;
	/** Quantity ordered. Must be ≥ 1. */
	quantity: number;
	/** Unit price in cents. */
	unitPriceCents: MoneyCents;
};

/** Delivery address for the order. */
export type DeliveryAddress = {
	street: string;
	city: string;
	state: string;
	postalCode: string;
	/** Optional delivery instructions (e.g. "leave at door"). */
	notes?: string;
};

/** Payment method — discriminated union on `type`. */
export type PaymentMethod =
	| { type: 'card'; last4: string; brand: string }
	| { type: 'wallet'; provider: 'apple-pay' | 'google-pay' }
	| { type: 'credits'; balanceCents: MoneyCents };

/**
 * Input passed to `workflow.startWorkflow` when placing a new food order.
 * This is the canonical start argument for `ORDER_FOOD_WORKFLOW`.
 */
export type OrderInput = {
	/** Idempotency key / order ID generated by the caller. */
	orderId: string;
	/** Non-empty list of ordered items. */
	items: OrderItem[];
	/** Delivery destination. */
	deliveryAddress: DeliveryAddress;
	/** Customer tier for priority routing and discounts. */
	customerTier: CustomerTier;
	/** Payment method used for this order. */
	paymentMethod: PaymentMethod;
	/** Restaurant identifier. */
	restaurantId: string;
	/** Customer identifier. */
	customerId: string;
	/** Optional promo code applied at placement time. */
	promoCode?: string;
	/** Override: maximum minutes the workflow waits for restaurant acceptance. Defaults to 10. */
	restaurantAcceptTimeoutMinutes?: number;
	/**
	 * Demo-only override for the number of courier location updates that triggers
	 * ContinueAsNew. Defaults to 100 so normal runs keep a production-shaped
	 * history-compaction threshold.
	 */
	historyCompactionThreshold?: number;
};

// ---------------------------------------------------------------------------
// Signals
// ---------------------------------------------------------------------------

/** Signal names accepted by the food-ordering workflow. */
export type SignalName =
	| 'cancelOrder'
	| 'restaurantAccepted'
	| 'restaurantRejected'
	| 'foodReady'
	| 'courierLocationUpdate'
	| 'addTip'
	| 'deliveryCompleted';

/** Payload for the `cancelOrder` signal. */
export type CancelOrderSignal = {
	/** Human-readable reason for cancellation. */
	reason: string;
};

/** Payload for the `restaurantAccepted` signal. */
export type RestaurantAcceptedSignal = {
	/** Estimated preparation time in minutes. */
	estimatedPrepMinutes: number;
};

/** Payload for the `restaurantRejected` signal. */
export type RestaurantRejectedSignal = {
	/** Human-readable reason for rejection. */
	reason: string;
	/** Whether the order could be retried with a different restaurant. */
	retryable: boolean;
};

/** Payload for the `foodReady` signal — emitted when kitchen preparation is complete. */
export type FoodReadySignal = Record<string, never>;

/** Payload for the `courierLocationUpdate` signal. */
export type CourierLocationUpdate = {
	/** Latitude in decimal degrees. */
	lat: number;
	/** Longitude in decimal degrees. */
	lng: number;
	/** Speed in km/h, if available from the courier device. */
	speedKmh?: number;
};

/** Payload for the `addTip` signal. */
export type AddTipSignal = {
	/** Tip amount in cents. Must be > 0. */
	amountCents: MoneyCents;
};

/** Payload for the `deliveryCompleted` signal. */
export type DeliveryCompletedSignal = Record<string, never>;

/**
 * Maps each {@link SignalName} to its payload type.
 * Use this to build type-safe signal-dispatch helpers and `setHandler` calls.
 */
export type SignalPayloadMap = {
	cancelOrder: CancelOrderSignal;
	restaurantAccepted: RestaurantAcceptedSignal;
	restaurantRejected: RestaurantRejectedSignal;
	foodReady: FoodReadySignal;
	courierLocationUpdate: CourierLocationUpdate;
	addTip: AddTipSignal;
	deliveryCompleted: DeliveryCompletedSignal;
};

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/** Query names exposed by the food-ordering workflow. */
export type QueryName = 'getStatus' | 'getTimeline';

/** Courier information included in an {@link OrderSnapshot}. */
export type CourierInfo = {
	/** Courier identifier. */
	courierId: string;
	/** Courier display name. */
	name: string;
	/** Last known location, populated once tracking begins. */
	location?: CourierLocationUpdate;
	/** Estimated time of arrival in minutes, if known. */
	etaMinutes?: number;
};

/** A compensation action recorded during saga rollback. */
export type CompensationRecord = {
	/** Identifier of the compensation step (e.g. `"refund-payment"`). */
	action: string;
	/** ISO-8601 timestamp of when the compensation executed. */
	timestamp: string;
	/** Whether the compensation activity succeeded. */
	ok: boolean;
	/** Captured error message if `ok` is false. */
	errorMessage?: string;
};

/**
 * Full queryable state of a live order workflow.
 * Returned by the `getStatus` query — this is what the control plane renders.
 */
export type OrderSnapshot = {
	/** Current order status. */
	status: OrderStatus;
	/** The original order input, including any mutable overrides (address, promo). */
	input: OrderInput;
	/** Sum of all item prices × quantities, in cents. */
	subtotalCents: MoneyCents;
	/** Delivery fee in cents. */
	deliveryFeeCents: MoneyCents;
	/** Tip in cents (updated by the `addTip` signal). */
	tipCents: MoneyCents;
	/** Promo discount in cents (0 if no promo applied). */
	promoDiscountCents: MoneyCents;
	/** Grand total after all adjustments, in cents. */
	totalCents: MoneyCents;
	/** Activity attempt counts keyed by activity type name. */
	attemptCounts: Record<string, number>;
	/** Compensation actions executed during any saga rollback. */
	compensations: CompensationRecord[];
	/** Courier information, populated once a courier is assigned. */
	courier?: CourierInfo;
	/** Number of courier location updates received (used to gate ContinueAsNew). */
	locationUpdateCount: number;
	/** ISO-8601 deadline by which the restaurant must accept before auto-cancel. */
	restaurantDeadline?: string;
	/** ISO-8601 deadline by which the courier must deliver before SLA breach. */
	deliveryDeadline?: string;
	/** ISO-8601 timestamp when the workflow execution started. */
	startedAt: string;
	/** ISO-8601 timestamp of the last state mutation. */
	updatedAt: string;
	/** ISO-8601 timestamp when the order reached a terminal state, if applicable. */
	completedAt?: string;
	/** Applied promo code string, if any. */
	appliedPromoCode?: string;
	/** Whether this run is about to call `continueAsNew`. */
	continueAsNewPending: boolean;
	/** Temporal search attribute values upserted at each status transition. */
	searchAttributes: {
		OrderStatus: OrderStatus;
		CustomerTier: CustomerTier;
		RestaurantId: string;
	};
};

/**
 * A single annotated entry in the order event timeline.
 * Returned by the `getTimeline` query and rendered by Track F's guided-tour panel.
 */
export type TimelineEntry = {
	/** Monotonically increasing index within this run's timeline. */
	index: number;
	/** ISO-8601 timestamp of the event. */
	timestamp: string;
	/** Human-readable description of what happened. */
	description: string;
	/** The order status at the time of this entry. */
	status: OrderStatus;
	/** Optional feature identifier for guided-tour highlighting. */
	featureId?: FeatureId;
	/** Optional Temporal or UI event type that advances the guided tour. */
	eventType?: WorkflowEventType | 'QueryCompleted' | 'WorkerRestarted';
};

/**
 * Maps each {@link QueryName} to its return type.
 * Use this to build type-safe query-dispatch helpers and `setHandler` calls.
 */
export type QueryReturnMap = {
	getStatus: OrderSnapshot;
	getTimeline: TimelineEntry[];
};

// ---------------------------------------------------------------------------
// Updates
// ---------------------------------------------------------------------------

/** Update names accepted by the food-ordering workflow. */
export type UpdateName = 'updateDeliveryAddress' | 'applyPromoCode';

/** Input for the `updateDeliveryAddress` update. */
export type UpdateDeliveryAddressInput = {
	/** New delivery address to apply to the order. */
	newAddress: DeliveryAddress;
};

/** Success return for `updateDeliveryAddress`. */
export type UpdateDeliveryAddressResult = {
	/** Whether the address was mutated (false if it was identical to the existing one). */
	updated: boolean;
	/** The address that is now effective on the order. */
	effectiveAddress: DeliveryAddress;
};

/**
 * Rejection reason for `updateDeliveryAddress`.
 * Returned synchronously by the validator before the handler runs.
 */
export type UpdateDeliveryAddressRejection =
	| 'order-already-in-delivery'
	| 'order-already-completed'
	| 'order-cancelled';

/** Input for the `applyPromoCode` update. */
export type ApplyPromoCodeInput = {
	/** The promo code string to validate and apply. */
	code: string;
};

/** Success return for `applyPromoCode`. */
export type ApplyPromoCodeResult = {
	/** Discount amount applied in cents. */
	discountCents: MoneyCents;
	/** New grand total after the discount, in cents. */
	newTotalCents: MoneyCents;
	/** Human-readable description of the promotion (e.g. `"10% off your order"`). */
	description: string;
};

/**
 * Rejection reason for `applyPromoCode`.
 * Returned synchronously by the validator before the handler runs.
 */
export type ApplyPromoCodeRejection =
	| 'invalid-code'
	| 'code-already-used'
	| 'code-expired'
	| 'order-already-completed'
	| 'order-cancelled';

/**
 * Maps each {@link UpdateName} to its input type.
 */
export type UpdateInputMap = {
	updateDeliveryAddress: UpdateDeliveryAddressInput;
	applyPromoCode: ApplyPromoCodeInput;
};

/**
 * Maps each {@link UpdateName} to its success return type.
 */
export type UpdateResultMap = {
	updateDeliveryAddress: UpdateDeliveryAddressResult;
	applyPromoCode: ApplyPromoCodeResult;
};

/**
 * Maps each {@link UpdateName} to its validator-rejection reason type.
 */
export type UpdateRejectionMap = {
	updateDeliveryAddress: UpdateDeliveryAddressRejection;
	applyPromoCode: ApplyPromoCodeRejection;
};

// ---------------------------------------------------------------------------
// Feature map
// ---------------------------------------------------------------------------

/**
 * Unique identifier for each Temporal feature demonstrated by the Sandman
 * food-ordering workflow. This is the authoritative list — Track F renders it
 * and the anti-drift coverage test checks it.
 */
export type FeatureId =
	| 'activities-retry'
	| 'non-retryable-failure'
	| 'saga-compensation'
	| 'signals'
	| 'queries'
	| 'updates-validators'
	| 'timers-durable-sleep'
	| 'child-workflow'
	| 'heartbeats-cancellation'
	| 'continue-as-new'
	| 'search-attributes'
	| 'local-activities'
	| 'replay-safety'
	| 'durable-recovery';

/**
 * Control-plane action identifier — maps to a button or interaction in the
 * sandbox control panel rendered by Track E.
 */
export type ControlId =
	| 'start-order'
	| 'cancel-order'
	| 'accept-restaurant'
	| 'reject-restaurant'
	| 'food-ready'
	| 'update-location'
	| 'add-tip'
	| 'update-address'
	| 'apply-promo'
	| 'complete-delivery'
	| 'kill-worker'
	| 'query-status'
	| 'query-timeline';

/**
 * One entry in the {@link FEATURES} list.
 * Every `signal`, `query`, `update`, and `control` reference in the list resolves
 * to a name in the corresponding union exported from this file.
 */
export type Feature = {
	/** Stable identifier for this feature. */
	id: FeatureId;
	/** The Temporal concept being demonstrated (rendered as a heading in Track F). */
	concept: string;
	/** How the concept is exercised in this specific workflow. */
	mechanic: string;
	/** Optional control-plane action that triggers or showcases this feature. */
	control?: ControlId;
	/** Optional signal that exercises this feature. */
	signal?: SignalName;
	/** Optional query that exercises this feature. */
	query?: QueryName;
	/** Optional update that exercises this feature. */
	update?: UpdateName;
};

/**
 * The complete list of Temporal features demonstrated by the Sandman
 * food-ordering workflow.
 *
 * Internal-consistency guarantee: every `signal`, `query`, `update`, and
 * `control` value in this list resolves to a member of the corresponding
 * union in this file.
 */
export const FEATURES = [
	{
		id: 'activities-retry',
		concept: 'Activities & Automatic Retry',
		mechanic:
			'Payment charge, restaurant notification, and courier dispatch each run as activities with configurable retry policies. Transient failures are automatically retried with exponential backoff.',
		control: 'start-order'
	},
	{
		id: 'non-retryable-failure',
		concept: 'Non-Retryable Failures',
		mechanic:
			'An invalid payment method or out-of-area address throws ApplicationFailure with nonRetryable: true, bypassing the retry policy and immediately triggering the saga compensation path.',
		control: 'start-order'
	},
	{
		id: 'saga-compensation',
		concept: 'Saga / Compensation',
		mechanic:
			'If the workflow fails after charging the customer, a compensation stack issues a refund. Each forward step registers a compensating action so the rollback is always symmetric.',
		control: 'cancel-order',
		signal: 'cancelOrder'
	},
	{
		id: 'signals',
		concept: 'Signals',
		mechanic:
			'Restaurant acceptance, rejection, food-ready, courier location, tip, and order cancellation all use Temporal signals. The workflow blocks on signal receipt using condition(), resuming only when the expected signal arrives.',
		control: 'accept-restaurant',
		signal: 'restaurantAccepted'
	},
	{
		id: 'queries',
		concept: 'Queries',
		mechanic:
			'getStatus returns a live OrderSnapshot of all workflow state without advancing execution. getTimeline returns the annotated event log consumed by the guided-tour panel.',
		control: 'query-status',
		query: 'getStatus'
	},
	{
		id: 'updates-validators',
		concept: 'Updates with Validators',
		mechanic:
			'updateDeliveryAddress is rejected synchronously by a validator if the order is already in delivery. applyPromoCode validates the code before mutating state, returning a typed rejection to the caller without re-driving the workflow.',
		control: 'update-address',
		update: 'updateDeliveryAddress'
	},
	{
		id: 'timers-durable-sleep',
		concept: 'Durable Timers / sleep()',
		mechanic:
			'A configurable deadline timer fires if the restaurant does not accept within N minutes, automatically triggering cancellation and saga compensation. The timer survives worker restarts.',
		control: 'start-order'
	},
	{
		id: 'child-workflow',
		concept: 'Child Workflows',
		mechanic:
			'Once a courier is assigned, the delivery leg is handed off to a DeliveryWorkflow child workflow. Its lifecycle is independently visible in the Temporal Web UI, demonstrating workflow composition.',
		control: 'complete-delivery',
		signal: 'deliveryCompleted'
	},
	{
		id: 'heartbeats-cancellation',
		concept: 'Activity Heartbeats & Cancellation',
		mechanic:
			'The courier-tracking activity heartbeats every 5 seconds with its latest location. Cancelling the order propagates cancellation to the activity via the heartbeat token, allowing a clean shutdown.',
		control: 'kill-worker',
		signal: 'courierLocationUpdate'
	},
	{
		id: 'continue-as-new',
		concept: 'ContinueAsNew',
		mechanic:
			'After 100 courier location updates, the workflow calls continueAsNew to keep event history bounded. The new run receives the current OrderSnapshot as its seed state so no data is lost.',
		signal: 'courierLocationUpdate'
	},
	{
		id: 'search-attributes',
		concept: 'Queryable Business Snapshot',
		mechanic:
			'The getStatus query returns the business fields you would normally index as Temporal search attributes: OrderStatus, CustomerTier, and RestaurantId. This keeps the v1 demo honest while still teaching which dimensions make executions searchable.',
		control: 'query-status',
		query: 'getStatus'
	},
	{
		id: 'local-activities',
		concept: 'Local Activities',
		mechanic:
			'Audit-log writes and metrics emission run as local activities (executed in the same process, no round-trip to the Temporal server) to demonstrate the durability/performance trade-off.',
		control: 'start-order'
	},
	{
		id: 'replay-safety',
		concept: 'Replay Safety',
		mechanic:
			'All non-deterministic operations (random IDs, current time, external HTTP calls) are wrapped in activities. The workflow function itself is a pure deterministic function of its history, as verified by the replayer.',
		query: 'getTimeline'
	},
	{
		id: 'durable-recovery',
		concept: 'Durable Recovery',
		mechanic:
			'The kill-worker button terminates the Node.js worker process mid-flight. Because the Temporal server preserves all workflow state, the workflow resumes exactly where it left off when the worker restarts — the centrepiece of the Sandman demo.',
		control: 'kill-worker'
	}
] as const satisfies Feature[];

/** Inferred type of the {@link FEATURES} constant. */
export type FeatureMap = typeof FEATURES;

// ---------------------------------------------------------------------------
// Teaching scenarios
// ---------------------------------------------------------------------------

/**
 * Stable identifiers for guided workshop scenarios. The IDs are shared by the
 * UI, documentation, and sandbox-template parity tests so the teaching path
 * cannot drift silently from the workflow contract.
 */
export const SCENARIO_ID = {
	HappyPath: 'happy-path',
	Retry: 'retry',
	TimeoutRefund: 'timeout-refund',
	UpdateRejection: 'update-rejection',
	ChildDelivery: 'child-delivery',
	WorkerRecovery: 'worker-recovery',
	ContinueAsNew: 'continue-as-new',
	ReplaySafety: 'replay-safety'
} as const;

/** Union of all guided workshop scenario identifiers. */
export type ScenarioId = (typeof SCENARIO_ID)[keyof typeof SCENARIO_ID];

/** A mechanically verifiable step in a guided scenario. */
export type ScenarioStep = {
	/** Stable step identifier within the scenario. */
	id: string;
	/** Control-plane action that drives the step, when the step is interactive. */
	control?: ControlId;
	/** Temporal concept the step is meant to teach. */
	featureId: FeatureId;
	/** Binary completion signal used by the UI and tests. */
	completesOn: WorkflowEventType | 'QueryCompleted' | 'WorkerRestarted';
};

/** One guided scenario exposed in the workshop UI. */
export type Scenario = {
	id: ScenarioId;
	title: string;
	summary: string;
	steps: readonly ScenarioStep[];
};

/** Canonical guided workshop scenarios for the Sandman demo. */
export const SCENARIOS = [
	{
		id: SCENARIO_ID.HappyPath,
		title: 'Deliver one order',
		summary:
			'Start the workflow, accept the order, update it, start the delivery child workflow, and complete delivery.',
		steps: [
			{
				id: 'start-workflow',
				control: 'start-order',
				featureId: 'activities-retry',
				completesOn: 'WorkflowExecutionStarted'
			},
			{
				id: 'restaurant-accepts',
				control: 'accept-restaurant',
				featureId: 'signals',
				completesOn: 'WorkflowExecutionSignaled'
			},
			{
				id: 'address-update',
				control: 'update-address',
				featureId: 'updates-validators',
				completesOn: 'WorkflowExecutionUpdateAccepted'
			},
			{
				id: 'delivery-child',
				control: 'food-ready',
				featureId: 'child-workflow',
				completesOn: 'ChildWorkflowExecutionStarted'
			},
			{
				id: 'complete-delivery',
				control: 'complete-delivery',
				featureId: 'child-workflow',
				completesOn: 'WorkflowExecutionCompleted'
			}
		]
	},
	{
		id: SCENARIO_ID.Retry,
		title: 'Watch activity retry',
		summary:
			'Use the transient-failure payment fixture to show Temporal retrying an activity without workflow-side retry loops.',
		steps: [
			{
				id: 'activity-completes-after-retry',
				control: 'start-order',
				featureId: 'activities-retry',
				completesOn: 'ActivityTaskCompleted'
			}
		]
	},
	{
		id: SCENARIO_ID.TimeoutRefund,
		title: 'Let the restaurant timeout refund the order',
		summary:
			'Start an order and do not accept it; the durable timer fires and compensation refunds the payment.',
		steps: [
			{
				id: 'restaurant-deadline',
				control: 'start-order',
				featureId: 'timers-durable-sleep',
				completesOn: 'TimerStarted'
			}
		]
	},
	{
		id: SCENARIO_ID.UpdateRejection,
		title: 'Reject an invalid update',
		summary:
			'Try to change the address after delivery begins so the update validator rejects before the handler mutates state.',
		steps: [
			{
				id: 'validator-rejects',
				control: 'update-address',
				featureId: 'updates-validators',
				completesOn: 'WorkflowExecutionUpdateRejected'
			}
		]
	},
	{
		id: SCENARIO_ID.ChildDelivery,
		title: 'Inspect the delivery child workflow',
		summary:
			'Start delivery and inspect the child workflow as a separate execution in Temporal Web.',
		steps: [
			{
				id: 'child-started',
				control: 'food-ready',
				featureId: 'child-workflow',
				completesOn: 'ChildWorkflowExecutionStarted'
			}
		]
	},
	{
		id: SCENARIO_ID.WorkerRecovery,
		title: 'Kill and restart the worker',
		summary:
			'Stop the worker while the workflow is waiting, then restart it and watch history replay restore execution.',
		steps: [
			{
				id: 'worker-restarted',
				control: 'kill-worker',
				featureId: 'durable-recovery',
				completesOn: 'WorkerRestarted'
			}
		]
	},
	{
		id: SCENARIO_ID.ContinueAsNew,
		title: 'Compact a long history',
		summary:
			'Run with a low history-compaction threshold and send courier location updates until ContinueAsNew starts a fresh run.',
		steps: [
			{
				id: 'continued-as-new',
				control: 'update-location',
				featureId: 'continue-as-new',
				completesOn: 'WorkflowExecutionContinuedAsNew'
			}
		]
	},
	{
		id: SCENARIO_ID.ReplaySafety,
		title: 'Replay the recorded history',
		summary:
			'Use the workflow test replayer to prove the workflow code is deterministic against a real event history.',
		steps: [
			{
				id: 'query-timeline',
				control: 'query-timeline',
				featureId: 'replay-safety',
				completesOn: 'QueryCompleted'
			}
		]
	}
] as const satisfies readonly Scenario[];

// ---------------------------------------------------------------------------
// Workflow event types (live event rail)
// ---------------------------------------------------------------------------

/**
 * Concrete Temporal history event type strings emitted during a food-ordering
 * workflow run. Each value is a valid `type` string for a `WorkflowEvent`
 * (see `src/lib/contracts/events.ts`).
 *
 * Track E uses these as completion predicates in the guided-tour rail and to
 * colour-code the live event stream.
 */
export const WORKFLOW_EVENT_TYPE = {
	WorkflowExecutionStarted: 'WorkflowExecutionStarted',
	WorkflowExecutionCompleted: 'WorkflowExecutionCompleted',
	WorkflowExecutionFailed: 'WorkflowExecutionFailed',
	WorkflowExecutionCanceled: 'WorkflowExecutionCanceled',
	WorkflowExecutionTerminated: 'WorkflowExecutionTerminated',
	WorkflowExecutionContinuedAsNew: 'WorkflowExecutionContinuedAsNew',
	ActivityTaskScheduled: 'ActivityTaskScheduled',
	ActivityTaskStarted: 'ActivityTaskStarted',
	ActivityTaskCompleted: 'ActivityTaskCompleted',
	ActivityTaskFailed: 'ActivityTaskFailed',
	ActivityTaskTimedOut: 'ActivityTaskTimedOut',
	ActivityTaskCancelRequested: 'ActivityTaskCancelRequested',
	ActivityTaskCanceled: 'ActivityTaskCanceled',
	TimerStarted: 'TimerStarted',
	TimerFired: 'TimerFired',
	TimerCanceled: 'TimerCanceled',
	WorkflowExecutionSignaled: 'WorkflowExecutionSignaled',
	WorkflowExecutionUpdateAccepted: 'WorkflowExecutionUpdateAccepted',
	WorkflowExecutionUpdateCompleted: 'WorkflowExecutionUpdateCompleted',
	WorkflowExecutionUpdateRejected: 'WorkflowExecutionUpdateRejected',
	ChildWorkflowExecutionStarted: 'ChildWorkflowExecutionStarted',
	ChildWorkflowExecutionCompleted: 'ChildWorkflowExecutionCompleted',
	ChildWorkflowExecutionFailed: 'ChildWorkflowExecutionFailed',
	StartChildWorkflowExecutionInitiated: 'StartChildWorkflowExecutionInitiated',
	MarkerRecorded: 'MarkerRecorded'
} as const;

/** Union of concrete Temporal history event type strings used by this workflow. */
export type WorkflowEventType = (typeof WORKFLOW_EVENT_TYPE)[keyof typeof WORKFLOW_EVENT_TYPE];
